#spring.application.name=SWP391project
server:
  port: 8080
  servlet:
    context-path: /swp391

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/swp"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    date-format: dd-MM-yyyy
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: "vinhhien8882004@gmail.com"
    password: "vvps ftmw mimc aohp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 36000 # in seconds

# Firebase Configuration
fcm:
  credentials:
    file:
      path: firebase-admin.json
cloudinary:
  cloud-name: dkfolzb8m
  api-key: 231453775362129
  api-secret: 0rsj4eImS-2gpngR2IuDfERT7XE

# Goong API Configuration
goong:
  api:
    key: "fYkDka9BdVPjFXwOG2Yoc2gyj15vfkdfC711wR8u"
  geocode:
    url: "https://rsapi.goong.io/geocode"
  distance:
    matrix:
      url: "https://rsapi.goong.io/DistanceMatrix"